language: bash
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_57f78a0846df_key -iv $encrypted_57f78a0846df_iv
  -in .travis/khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo "TZ='Asia/Shanghai'; export TZ" >> ~/.profile
- ". ~/.profile"
- date
- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"
- docker pull khs1994/gitbook:1.0.0
script:
- cd ~
- export REPO=$REPO
- export REPO_ALIYUN=$REPO_ALIYUN
- "~/build/khs1994-website/php-docs/.travis/deploy.sh"
- cd ~
env:
  global:
  - DEPLOY_BRANCH: gh-pages
  - REPO: git@github.com:khs1994-website/php-docs.git
  - REPO_ALIYUN: git@code.aliyun.com:khs1994-website/php-docs.git
addons:
  ssh_known_hosts:
  - code.aliyun.com
  - github.com
branches:
  only:
  - master
  - gitbook
